apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chpod
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/chpod
      sourceRef:
        kind: GitRepository
        name: https://github.com/winterlyembrace/chpod.git
  values:
    backend:
      image:
        tag: "v1.0.0" # {"$imagepolicy": "flux-system:backend-policy"}
    frontend:
      image:
        tag: "v1.0.0" # {"$imagepolicy": "flux-system:frontend-policy"}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: backend-repo
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend-repo
  policy:
    semver:
      range: '>=1.0.0'