apiVersion: v1
kind: Secret
metadata:
  name: main-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kubernetes-admin@kubernetes
  server: "https://192.168.122.200:6443"
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }