apiVersion: v1
kind: Secret
metadata:
  name: k8s-gitops-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/winterlyembrace/k8s-gitops-config.git
