apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram-config
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-telegram-config
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ['alertname', 'job']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: 'telegram'
          receivers:
          - name: 'telegram'
            telegram_configs:
            - bot_token: "{{ .token }}"  
              chat_id: {{ .chat_id }}    
              send_resolved: true
              parse_mode: 'HTML'
              message: |-
                <b>{{ "{{" }} .Status | toUpper {{ "}}" }}</b>
                <b>Alert:</b> {{ "{{" }} .CommonAnnotations.summary {{ "}}" }}
                <b>Severity:</b> {{ "{{" }} .CommonLabels.severity {{ "}}" }}
  data:
  - secretKey: token
    remoteRef:
      key: monitoring/telegram
      property: token
  - secretKey: chat_id
    remoteRef:
      key: monitoring/telegram
      property: chat_id
