---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgApMKiuhYtDcaXkoe4NKPNbQpPOcw3TYOJkDdxkb2Rs3L5ZFRVdNFMWIfbABu8Aq2yA2/ShxaegTlT3tPxqMFRw7S96KMfoEDNObKk4uZ9qofu9SquB4nLVlragFRSKi7+KVxd3IBfpDcImesXK4vRavyL/Mvgs74ydFPpSm77uVpFae7oGrM8fpR38v3dJ7UABiI6ZAs7iYxf55USxqgYWdAjWDikyeNn/rFhrfTH3/V8mvyPTAgoQ3WYF2dM63h8OLaZfjnIfyuz2pJmdI45roP3AhFGviRa657WoENl1gcFhkSCytw2BbJotSkAlLdLOCXGIOyQpp/Ia23IhGHxcrqkgWj8rGjoM9CsndIBmwsh38ZlMGl2yUAP832A7gLBne8FdFEZZWvCEP+YfnMmZIL3cpbAD3xqNHjHGLuWKPNYViZGv/KRM5P64/HK2tXnyAsq5Gkb7SadEnbqkUCa7zOSDbB+l6zZKeAQmrwOHMGeZf5maHWayoguXq9Q+HkedQAzyedv4Scuss4PHKM/EoXKoGKp9fpuzAgO5IvwM2YJZ7XVJBWxdLYXcVzIbGrsU1mB5gDrsb91y/9KrWkhBrgQpbhyMenBIWQsbR0337JmqD/PQ4ARsK7ZkAV1ESLsqRNuIB14ueEKCspHyvJId+dydS5UOQpGGPIlprUlO1tR9x9Es7QCeriA9EwPV3tFaNREy
  template:
    metadata:
      name: vault-token
      namespace: flux-system
    type: Opaque
