apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-l2-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://192.168.122.200:6443'
  project: default
  source:
    path: cilium-config
    repoURL: https://github.com/winterlyembrace/k8s-gitops-config.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
---
