apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.15.2
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: true
        k8sServiceHost: 192.168.122.200
        k8sServicePort: 6443
        l2announcements:
          enabled: true
        externalIPs:
          enabled: true
            
        ipam:
          mode: "kubernetes"
        
        operator:
          prometheus:
            enabled: true
          replicas: 1
  destination:
    server: 192.168.122.200
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true