apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: libvirt-ssh-key
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: libvirt-ssh-key
    creationPolicy: Owner
  data:
    - secretKey: id_rsa
      remoteRef:
        key: secret/libvirt/ssh
        property: id_rsa 