apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 82.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: "admin-user"
        passwordKey: "admin-password"
      ingress:
        enabled: true
    prometheus:
      prometheusSpec:
        retention: 10d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    # Settings for k3d:
    prometheus-node-exporter:
      hostRootfs: false
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9100"
