apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: "l2-policy"
spec:
  serviceSelector: {}
  nodeSelector:
    matchLabels:
      node-role.com/type: worker
  interfaces:
    - ens4
  externalIPs: true
  loadBalancerIPs: true
