apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/overlays/mgmt-cluster/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers 
  interval: 1h
  path: ./infrastructure/overlays/mgmt-cluster/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-infra
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/controllers/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-operator-infra
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-infra
  interval: 1h
  path: ./infrastructure/controllers/vault-config-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
